version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=production
      - PORT=3000
      - REDIS_HOST=localhost
      - REDIS_PORT=6379
      - RECALLAI_API_KEY=${RECALLAI_API_KEY}
      - WEBHOOK_BASE_URL=${WEBHOOK_BASE_URL:-http://localhost:3000}
    volumes:
      - .:/app
      - /app/node_modules
    restart: unless-stopped